[package]
name = "rust-ping"
version = "0.1.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = "3.0.0-beta.2"
ping = "0.2.0"
anyhow = "1.0.41"
rand = "0.8.4"